apiVersion: apps/v1
kind: Deployment
metadata:
  name: labkes-frontend-app
  namespace: pikobar-labkes
  labels:
    app: labkes-frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: labkes-frontend-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: labkes-frontend-app
    spec:
      automountServiceAccountToken: false
      containers:
        - name: labkes-frontend-app
          image: registry.digitalservice.id/labkes-pikobar/frontend-labkes-production:%VERSION%
          ports:
            - containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "250m"
      imagePullSecrets:
        - name: regcred-labkes
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/os
                operator: In
                values:
                - linux 
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - jds-rancher-node-01
                - jds-rancher-node-02
                - jds-rancher-node-03
                - jds-rancher-node-04